[package]
name = "purr-binding"
version = "0.1.0"
authors = ["chux0519 <chuxdesign@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "purrmitive_rust"
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.15"
